server.port=${PORT:8080}
server.forward-headers-strategy=native
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.same-site=none

spring.datasource.url=${JDBC_DATABASE_URL}
spring.datasource.username=${JDBC_DATABASE_USERNAME}
spring.datasource.password=${JDBC_DATABASE_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

plaid.client-id=${PLAID_CLIENT_ID}
plaid.secret=${PLAID_SECRET}
plaid.env=${PLAID_ENV:production}